version: "3.7"
services:
  frontend:
    restart: always
    command: npm start
    container_name: medqcx-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  